/** Server-safe lead event types for API — no src/lib imports. */

export type LeadEventType =
  | 'created'
  | 'duplicate_blocked'
  | 'missed_call_again'
  | 'assigned'
  | 'status_change'
  | 'contact_attempted'
  | 'contact_note'
  | 'call_attempted'
  | 'sms_attempted'
  | 'second_attempt_started'
  | 'third_attempt_started'
  | 'fourth_attempt_started'
  | 'fifth_attempt_started'
  | 'sixth_attempt_started'
  | 'booked'
  | 'booking_cancelled'
  | 'completed'
  | 'lost'
  | 'expired'
  | 'unassigned'
  | 'review_request'
  | 'sms_sent'
  | 'invoice_sent'
  | 'invoice_paid_manual'
  | 'deleted'
  | 'extraction_retried'
  | 'voicemail_enriched'
  | 'quote_sms_sent'
  | 'quote_accepted'
  | 'quote_declined'
  | 'booking_confirm_sms'
  | 'booking_reminder_sent'
